[project]
name = "jellyfin-rpc"
version = "1.6.3"
description = "Discord RPC for Jellyfin"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Ken Sible", email = "ksible@outlook.com" }]
requires-python = ">=3.12,<4.0"
dependencies = [
    "jellyfin-apiclient-python>=1.11.0",
    "pypresence@git+https://github.com/qwertyquerty/pypresence",
]

[project.optional-dependencies]
gui = ["customtkinter>=5.2.2", "pystray>=0.19.5", "pyinstaller>=6.17.0"]

[dependency-groups]
dev = ["ruff>=0.14.6", "mypy>=1.18.2"]

[project.urls]
homepage = "https://github.com/kennethsible/jellyfin-rpc"

[project.scripts]
jellyfin-rpc = "jellyfin_rpc.jellyfin_rpc:main"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
ignore_missing_imports = true

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"
